import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Comic+Neue:ital,wght@0,300;1,400&family=Lato&family=Open+Sans:wght@300&family=Roboto&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className="text-center">
          <h2 className="align-middle">
            Hi, I'm <span>Nadim</span>
          </h2>
          <h2>A React Native Developer</h2>
        </div>
        <p>
          I'm a react native developer sepcializing in building exceptional
          apps. Currently I'm focused on updating and imporiving my apps.
        </p>
      </main>
    </div>
  );
};

export default Home;
